           Failed to locate the largest file in {{ search_dir }}.
              Error: {{ ansible_failed_result.msg }}
      always:
        - name: Clear temporary facts for subsequent runs
          ansible.builtin.meta: clear_facts
          # Ensures a clean state for later executions